### ISSUE TITLE
GPG failed to sign the data

### ISSUE THREAD

**Issue by tovbinm** [scala-steward-org/scala-steward-action#2]
We are getting the following error. Any recommendations on how to troubleshoot this?

```
java.io.IOException: 'git commit --all -m Update xyz to 1.2.3 --gpg-sign' exited with code 128
error: gpg failed to sign the data
fatal: failed to write commit object

	at org.scalasteward.core.io.process$.$anonfun$slurp$9(process.scala:48)
	at org.scalasteward.core.io.process$.$anonfun$slurp$9$adapted(process.scala:44)
	at cats.effect.internals.IORunLoop$.cats$effect$internals$IORunLoop$$loop(IORunLoop.scala:145)
	at cats.effect.internals.IORunLoop$RestartCallback.signal(IORunLoop.scala:366)
	at cats.effect.internals.IORunLoop$RestartCallback.apply(IORunLoop.scala:387)
	at cats.effect.internals.IORunLoop$RestartCallback.apply(IORunLoop.scala:330)
	at cats.effect.internals.IORunLoop$.cats$effect$internals$IORunLoop$$loop(IORunLoop.scala:141)
	at cats.effect.internals.IORunLoop$RestartCallback.signal(IORunLoop.scala:366)
	at cats.effect.internals.IORunLoop$RestartCallback.apply(IORunLoop.scala:387)
	at cats.effect.internals.IORunLoop$RestartCallback.apply(IORunLoop.scala:330)
	at cats.effect.internals.IORunLoop$.cats$effect$internals$IORunLoop$$loop(IORunLoop.scala:141)
	at cats.effect.internals.IORunLoop$RestartCallback.signal(IORunLoop.scala:366)
	at cats.effect.internals.IORunLoop$RestartCallback.apply(IORunLoop.scala:387)
	at cats.effect.internals.IORunLoop$RestartCallback.apply(IORunLoop.scala:330)
	at cats.effect.internals.IOShift$Tick.run(IOShift.scala:36)
	at cats.effect.internals.PoolUtils$$anon$2$$anon$3.run(PoolUtils.scala:52)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
```

**Comment by tovbinm** [comment]
Ideas? @alejandrohdezma @fthomas

**Comment by alejandrohdezma** [comment]
Hey @tovbinm, can you try using the key you are adding via `gpg-secret-key` locally with a `git commit -s`? Just to discard any problems with the GPG key

**Comment by tovbinm** [comment]
Yes, commit signing works with that key for me. I also added the GPG key to my Github account (though it wasnt mentioned in the README)

**Comment by tovbinm** [comment]
I can also see in the logs that it reads and sets it correctly:
```
Setting github repository to ***/***
gpg: directory '/github/home/.gnupg' created
gpg: keybox '/github/home/.gnupg/pubring.kbx' created
gpg: /github/home/.gnupg/trustdb.gpg: trustdb created
gpg: key XXXXXXXXXXXXXXX: public key "Scala Steward <xyz@abc.zzz>" imported
gpg: key XXXXXXXXXXXXXXX: secret key imported
gpg: Total number processed: 1
gpg:               imported: 1
gpg:       secret keys read: 1
gpg:   secret keys imported: 1
2020-05-06 18:38:49,400 INFO   
```

**Comment by alejandrohdezma** [comment]
> Yes, commit signing works with that key for me. I also added the GPG key to my Github account (though it wasnt mentioned in the README)

Thanks for that! I added a [PR](https://github.com/scala-steward-org/scala-steward-action/pull/4) adding it to the `README`

**Comment by tovbinm** [comment]
Well, it only works locally on my machine ;) The github actions run stills fails.

**Comment by alejandrohdezma** [comment]
@tovbinm Is your key a 4096 key? That's [necessary for the Github Action](https://github.com/scala-steward-org/scala-steward-action/blob/master/entrypoint.sh#L61) (and Github) to import the key to Git correctly

**Comment by alejandrohdezma** [comment]
Which I realized it is also not indicated in the README, I'll fix that

**Comment by tovbinm** [comment]
No, mine is 2048. Let me try 4096 one.

**Comment by tovbinm** [comment]
Worked!

**Comment by alejandrohdezma** [comment]
Great! I'll add that step to the README so it doesn't bother others. Thank you very much for finding that :)

**Comment by tovbinm** [comment]
Thank you!

**Comment by tovbinm** [comment]
FYI, this is the command I used on Mac to generate the key:
```bash
gpg --default-new-key-algo rsa4096 --gen-key
```
