### ISSUE TITLE
scala-steward-action version 2.13.2 keeps failing not able to download the dependencies

### ISSUE THREAD

**Issue by tovbinm** [scala-steward-org/scala-steward-action#229]
Any ideas on what's wrong? Thanks in advance.

```
  java.io.IOException: '"SBT_OPTS=-Xmx2048m -Xss8m -XX:MaxMetaspaceSize=512m" sbt -Dsbt.color=false -Dsbt.log.noformat=true -Dsbt.supershell=false ;+ stewardDependencies;reload plugins;stewardDependencies' exited with code 1
  copying runtime jar...
  [info] [launcher] getting org.scala-sbt sbt 1.5.0  (this may take some time)...
  [info] [launcher] getting Scala 2.12.13 (for sbt)...
  [info] welcome to sbt 1.5.0 (Azul Systems, Inc. Java 11.0.10)
  [info] loading global plugins from /home/runner/.sbt/1.0/plugins
  [info] compiling 1 Scala source to /home/runner/.sbt/1.0/plugins/target/scala-2.12/sbt-1.0/classes ...
  [info] Non-compiled module 'compiler-bridge_2.12' for Scala 2.12.13. Compiling...
  [info]   Compilation completed in 10.825s.
  [info] done compiling
  [info] loading settings for project poseidon-build from plugins.sbt ...
  [info] loading project definition from /home/runner/scala-steward/workspace/repos/faros-ai/poseidon/project
  [warn] 
  [warn] 	Note: Some unresolved dependencies have extra attributes.  Check that these dependencies exist with the requested attributes.
  [warn] 		com.simplytyped:sbt-antlr4:0.8.3 (sbtVersion=1.0, scalaVersion=2.12)
  [warn] 		com.typesafe.sbt:sbt-native-packager:1.8.1 (sbtVersion=1.0, scalaVersion=2.12)
  [warn] 		com.typesafe.sbt:sbt-git:1.0.0 (sbtVersion=1.0, scalaVersion=2.12)
  [warn] 		com.github.cb372:sbt-explicit-dependencies:0.2.16 (sbtVersion=1.0, scalaVersion=2.12)
  [warn] 
  [warn] 	Note: Unresolved dependencies path:
  Error:  sbt.librarymanagement.ResolveException: Error downloading com.simplytyped:sbt-antlr4;sbtVersion=1.0;scalaVersion=2.12:0.8.3
  Error:    Not found
  Error:    Not found
  Error:    not found: repo1.maven.org/maven2/com/simplytyped/sbt-antlr4_2.12_1.0/0.8.3/sbt-antlr4-0.8.3.pom
  Error:    not found: /home/runner/.ivy2/localcom.simplytyped/sbt-antlr4/scala_2.12/sbt_1.0/0.8.3/ivys/ivy.xml
  Error:    forbidden: repo.scala-sbt.org/scalasbt/sbt-plugin-releases/com.simplytyped/sbt-antlr4/scala_2.12/sbt_1.0/0.8.3/ivys/ivy.xml
  Error:    forbidden: repo.typesafe.com/typesafe/ivy-releases/com.simplytyped/sbt-antlr4/scala_2.12/sbt_1.0/0.8.3/ivys/ivy.xml
  Error:  Error downloading com.typesafe.sbt:sbt-native-packager;sbtVersion=1.0;scalaVersion=2.12:1.8.1
  Error:    Not found
  Error:    Not found
  Error:    not found: repo1.maven.org/maven2/com/typesafe/sbt/sbt-native-packager_2.12_1.0/1.8.1/sbt-native-packager-1.8.1.pom
  Error:    not found: /home/runner/.ivy2/localcom.typesafe.sbt/sbt-native-packager/scala_2.12/sbt_1.0/1.8.1/ivys/ivy.xml
  Error:    forbidden: repo.scala-sbt.org/scalasbt/sbt-plugin-releases/com.typesafe.sbt/sbt-native-packager/scala_2.12/sbt_1.0/1.8.1/ivys/ivy.xml
  Error:    forbidden: repo.typesafe.com/typesafe/ivy-releases/com.typesafe.sbt/sbt-native-packager/scala_2.12/sbt_1.0/1.8.1/ivys/ivy.xml
  Error:  Error downloading com.typesafe.sbt:sbt-git;sbtVersion=1.0;scalaVersion=2.12:1.0.0
  Error:    Not found
  Error:    Not found
  Error:    not found: repo1.maven.org/maven2/com/typesafe/sbt/sbt-git_2.12_1.0/1.0.0/sbt-git-1.0.0.pom
  Error:    not found: /home/runner/.ivy2/localcom.typesafe.sbt/sbt-git/scala_2.12/sbt_1.0/1.0.0/ivys/ivy.xml
  Error:    forbidden: repo.scala-sbt.org/scalasbt/sbt-plugin-releases/com.typesafe.sbt/sbt-git/scala_2.12/sbt_1.0/1.0.0/ivys/ivy.xml
  Error:    forbidden: repo.typesafe.com/typesafe/ivy-releases/com.typesafe.sbt/sbt-git/scala_2.12/sbt_1.0/1.0.0/ivys/ivy.xml
  Error:  Error downloading com.github.cb372:sbt-explicit-dependencies;sbtVersion=1.0;scalaVersion=2.12:0.2.16
  Error:    Not found
  Error:    Not found
  Error:    not found: repo1.maven.org/maven2/com/github/cb372/sbt-explicit-dependencies_2.12_1.0/0.2.16/sbt-explicit-dependencies-0.2.16.pom
  Error:    not found: /home/runner/.ivy2/localcom.github.cb372/sbt-explicit-dependencies/scala_2.12/sbt_1.0/0.2.16/ivys/ivy.xml
  Error:    forbidden: repo.scala-sbt.org/scalasbt/sbt-plugin-releases/com.github.cb372/sbt-explicit-dependencies/scala_2.12/sbt_1.0/0.2.16/ivys/ivy.xml
  Error:    forbidden: repo.typesafe.com/typesafe/ivy-releases/com.github.cb372/sbt-explicit-dependencies/scala_2.12/sbt_1.0/0.2.16/ivys/ivy.xml
  Error:  	at lmcoursier.CoursierDependencyResolution.unresolvedWarningOrThrow(CoursierDependencyResolution.scala:258)
  Error:  	at lmcoursier.CoursierDependencyResolution.$anonfun$update$38(CoursierDependencyResolution.scala:227)
  Error:  	at scala.util.Either$LeftProjection.map(Either.scala:573)
  Error:  	at lmcoursier.CoursierDependencyResolution.update(CoursierDependencyResolution.scala:227)
  Error:  	at sbt.librarymanagement.DependencyResolution.update(DependencyResolution.scala:60)
  Error:  	at sbt.internal.LibraryManagement$.resolve$1(LibraryManagement.scala:59)
  Error:  	at sbt.internal.LibraryManagement$.$anonfun$cachedUpdate$12(LibraryManagement.scala:133)
  Error:  	at sbt.util.Tracked$.$anonfun$lastOutput$1(Tracked.scala:73)
  Error:  	at sbt.internal.LibraryManagement$.$anonfun$cachedUpdate$20(LibraryManagement.scala:146)
  Error:  	at scala.util.control.Exception$Catch.apply(Exception.scala:228)
  Error:  	at sbt.internal.LibraryManagement$.$anonfun$cachedUpdate$11(LibraryManagement.scala:146)
  Error:  	at sbt.internal.LibraryManagement$.$anonfun$cachedUpdate$11$adapted(LibraryManagement.scala:127)
  Error:  	at sbt.util.Tracked$.$anonfun$inputChangedW$1(Tracked.scala:219)
  Error:  	at sbt.internal.LibraryManagement$.cachedUpdate(LibraryManagement.scala:160)
  Error:  	at sbt.Classpaths$.$anonfun$updateTask0$1(Defaults.scala:3670)
  Error:  	at scala.Function1.$anonfun$compose$1(Function1.scala:49)
  Error:  	at sbt.internal.util.$tilde$greater.$anonfun$$u2219$1(TypeFunctions.scala:62)
  Error:  	at sbt.std.Transform$$anon$4.work(Transform.scala:68)
  Error:  	at sbt.Execute.$anonfun$submit$2(Execute.scala:282)
  Error:  	at sbt.internal.util.ErrorHandling$.wideConvert(ErrorHandling.scala:23)
  Error:  	at sbt.Execute.work(Execute.scala:291)
  Error:  	at sbt.Execute.$anonfun$submit$1(Execute.scala:282)
  Error:  	at sbt.ConcurrentRestrictions$$anon$4.$anonfun$submitValid$1(ConcurrentRestrictions.scala:265)
  Error:  	at sbt.CompletionService$$anon$2.call(CompletionService.scala:64)
  Error:  	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
  Error:  	at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:515)
  Error:  	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
  Error:  	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
  Error:  	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
  Error:  	at java.base/java.lang.Thread.run(Thread.java:834)
  Error:  (update) sbt.librarymanagement.ResolveException: Error downloading com.simplytyped:sbt-antlr4;sbtVersion=1.0;scalaVersion=2.12:0.8.3
  Error:    Not found
  Error:    Not found
  Error:    not found: repo1.maven.org/maven2/com/simplytyped/sbt-antlr4_2.12_1.0/0.8.3/sbt-antlr4-0.8.3.pom
  Error:    not found: /home/runner/.ivy2/localcom.simplytyped/sbt-antlr4/scala_2.12/sbt_1.0/0.8.3/ivys/ivy.xml
  Error:    forbidden: repo.scala-sbt.org/scalasbt/sbt-plugin-releases/com.simplytyped/sbt-antlr4/scala_2.12/sbt_1.0/0.8.3/ivys/ivy.xml
  Error:    forbidden: repo.typesafe.com/typesafe/ivy-releases/com.simplytyped/sbt-antlr4/scala_2.12/sbt_1.0/0.8.3/ivys/ivy.xml
  Error:  Error downloading com.typesafe.sbt:sbt-native-packager;sbtVersion=1.0;scalaVersion=2.12:1.8.1
  Error:    Not found
  Error:    Not found
  Error:    not found: repo1.maven.org/maven2/com/typesafe/sbt/sbt-native-packager_2.12_1.0/1.8.1/sbt-native-packager-1.8.1.pom
  Error:    not found: /home/runner/.ivy2/localcom.typesafe.sbt/sbt-native-packager/scala_2.12/sbt_1.0/1.8.1/ivys/ivy.xml
  Error:    forbidden: repo.scala-sbt.org/scalasbt/sbt-plugin-releases/com.typesafe.sbt/sbt-native-packager/scala_2.12/sbt_1.0/1.8.1/ivys/ivy.xml
  Error:    forbidden: repo.typesafe.com/typesafe/ivy-releases/com.typesafe.sbt/sbt-native-packager/scala_2.12/sbt_1.0/1.8.1/ivys/ivy.xml
  Error:  Error downloading com.typesafe.sbt:sbt-git;sbtVersion=1.0;scalaVersion=2.12:1.0.0
  Error:    Not found
  Error:    Not found
  Error:    not found: repo1.maven.org/maven2/com/typesafe/sbt/sbt-git_2.12_1.0/1.0.0/sbt-git-1.0.0.pom
  Error:    not found: /home/runner/.ivy2/localcom.typesafe.sbt/sbt-git/scala_2.12/sbt_1.0/1.0.0/ivys/ivy.xml
  Error:    forbidden: repo.scala-sbt.org/scalasbt/sbt-plugin-releases/com.typesafe.sbt/sbt-git/scala_2.12/sbt_1.0/1.0.0/ivys/ivy.xml
  Error:    forbidden: repo.typesafe.com/typesafe/ivy-releases/com.typesafe.sbt/sbt-git/scala_2.12/sbt_1.0/1.0.0/ivys/ivy.xml
  Error:  Error downloading com.github.cb372:sbt-explicit-dependencies;sbtVersion=1.0;scalaVersion=2.12:0.2.16
  Error:    Not found
  Error:    Not found
  Error:    not found: repo1.maven.org/maven2/com/github/cb372/sbt-explicit-dependencies_2.12_1.0/0.2.16/sbt-explicit-dependencies-0.2.16.pom
  Error:    not found: /home/runner/.ivy2/localcom.github.cb372/sbt-explicit-dependencies/scala_2.12/sbt_1.0/0.2.16/ivys/ivy.xml
  Error:    forbidden: repo.scala-sbt.org/scalasbt/sbt-plugin-releases/com.github.cb372/sbt-explicit-dependencies/scala_2.12/sbt_1.0/0.2.16/ivys/ivy.xml
  Error:    forbidden: repo.typesafe.com/typesafe/ivy-releases/com.github.cb372/sbt-explicit-dependencies/scala_2.12/sbt_1.0/0.2.16/ivys/ivy.xml
  [warn] Project loading failed: (r)etry, (q)uit, (l)ast, or (i)gnore? (default: r)
  
  	at org.scalasteward.core.io.process$.$anonfun$slurp$9(process.scala:58)
  	at org.scalasteward.core.io.process$.$anonfun$slurp$9$adapted(process.scala:54)
  	at delay$extension @ fs2.io.package$.readBytesFromInputStream(io.scala:95)
  	at map @ fs2.internal.CompileScope.$anonfun$close$9(CompileScope.scala:246)
  	at flatMap @ fs2.internal.CompileScope.$anonfun$close$6(CompileScope.scala:245)
  	at map @ fs2.internal.CompileScope.fs2$internal$CompileScope$$traverseError(CompileScope.scala:222)
  	at flatMap @ fs2.internal.CompileScope.$anonfun$close$4(CompileScope.scala:244)
  	at map @ fs2.internal.CompileScope.fs2$internal$CompileScope$$traverseError(CompileScope.scala:222)
  	at flatMap @ fs2.internal.CompileScope.$anonfun$close$2(CompileScope.scala:242)
  	at flatMap @ fs2.internal.CompileScope.close(CompileScope.scala:241)
  	at main$ @ org.scalasteward.core.Main$.main(Main.scala:22)
  	at flatMap @ fs2.internal.FreeC$.interruptGuard$1(Algebra.scala:436)
  	at flatMap @ fs2.internal.CompileScope.$anonfun$openAncestor$2(CompileScope.scala:261)
  	at flatMap @ fs2.internal.FreeC$.$anonfun$compile$17(Algebra.scala:545)
  	at map @ fs2.internal.CompileScope.$anonfun$close$9(CompileScope.scala:246)
  2021-04-12 17:24:52,344 INFO  ──────────── Total time: Steward faros-ai/poseidon: 42s 799ms ────────────
  2021-04-12 17:24:52,346 INFO  ──────────── Total time: run: 43s 874ms ────────────
Error:  ✕ Launching org.scala-steward:scala-steward-core_2.13:0.9.1 failed
```

**Comment by fthomas** [comment]
Probably because of https://twitter.com/SethTisue/status/1381624559296675846.

**Comment by tovbinm** [comment]
Oh, bummer. Thanks. Guess we would need to wait...

**Comment by alejandrohdezma** [comment]
I would keep this issue open until the issue is fixed in case someone else discovers this error because of the action

**Comment by fthomas** [comment]
@tovbinm Is it working again?

**Comment by tovbinm** [comment]
Yes, thank you.
