### ISSUE TITLE
Action failing with "java.lang.NoClassDefFoundError: scala/Serializable"

### ISSUE THREAD

**Issue by paoloboni** [scala-steward-org/scala-steward-action#244]
Hi,

I just added the following action to a private Github repo:
```
---
name: Launch Scala Steward

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]
  schedule:
    - cron: '0 0 * * 0'

jobs:
  scala-steward:
    runs-on: ubuntu-latest
    name: Launch Scala Steward
    steps:
      - name: Launch Scala Steward
        uses: scala-steward-org/scala-steward-action@v2
        with:
          github-token: ${{ github.token }}
```

The action fails as below:
```
  2021-05-03 10:22:07,921 ERROR Steward XXX/YYY failed
  java.io.IOException: '"SBT_OPTS=-Xmx2048m -Xss8m -XX:MaxMetaspaceSize=512m" sbt -Dsbt.color=false -Dsbt.log.noformat=true -Dsbt.supershell=false ;+ stewardDependencies;reload plugins;stewardDependencies' exited with code 1
  copying runtime jar...
  [info] [launcher] getting org.scala-sbt sbt 1.4.2  (this may take some time)...
  [info] [launcher] getting Scala 2.13.3 (for sbt)...
  java.lang.NoClassDefFoundError: scala/Serializable
  	at sbt.internal.ClassLoaderWarmup$.warmup(XMainConfiguration.scala:31)
  	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
  	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
  	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
  	at java.base/java.lang.reflect.Method.invoke(Method.java:566)
  	at sbt.internal.XMainConfiguration.run(XMainConfiguration.scala:82)
  	at sbt.xMain.run(Main.scala:46)
  	at xsbt.boot.Launch$.$anonfun$run$1(Launch.scala:149)
  	at xsbt.boot.Launch$.withContextLoader(Launch.scala:176)
  	at xsbt.boot.Launch$.run(Launch.scala:149)
  	at xsbt.boot.Launch$.$anonfun$apply$1(Launch.scala:44)
  	at xsbt.boot.Launch$.launch(Launch.scala:159)
  	at xsbt.boot.Launch$.apply(Launch.scala:44)
  	at xsbt.boot.Launch$.apply(Launch.scala:21)
  	at xsbt.boot.Boot$.runImpl(Boot.scala:78)
  	at xsbt.boot.Boot$.run(Boot.scala:73)
  	at xsbt.boot.Boot$.main(Boot.scala:21)
  	at xsbt.boot.Boot.main(Boot.scala)
  Caused by: java.lang.ClassNotFoundException: scala.Serializable
  	at java.base/java.net.URLClassLoader.findClass(URLClassLoader.java:471)
  	at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:589)
  	at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:522)
  	... 18 more
  Error:  [launcher] error during sbt launcher: java.lang.NoClassDefFoundError: scala/Serializable
```
I can see from the logs the version of scala-steward running is 0.9.1.
I tried specifying the JDK version, first setting it to 11 then to 8, but getting the same result.
Does anyone have any idea/suggestion on how to fix this problem?
Many thanks

**Comment by alejandrohdezma** [comment]
This seems to be similar to [this question](https://users.scala-lang.org/t/java-lang-noclassdeffounderror-scala-serializable/5669). Are you using a fixed version of kind-projector (or any other compiler plugin) compiled with an older Scala version?

**Comment by paoloboni** [comment]
But isn't that error related to the execution of scala-steward? Isn't that an isolated process? I'm not sure I understand how that process can possibly fail based on how my project is configured.

**Comment by alejandrohdezma** [comment]
Scala Steward runs as an SBT plugin inside your project, so if your project's build is broken, Scala Steward run will fail

**Comment by alejandrohdezma** [comment]
@paoloboni https://github.com/scala-steward-org/scala-steward/blob/master/modules/sbt-plugin/src/main/scala/org/scalasteward/sbt/plugin/StewardPlugin.scala

Scala Steward injects that plugin ☝🏼 into your build to get the current dependencies/versions

**Comment by paoloboni** [comment]
Ok thanks for clarifying this. Perhaps it would be good to have it explained somewhere on [this page](https://github.com/scala-steward-org/scala-steward)?
I'm going to close this as this is something that needs to be investigated on my side.

**Comment by alejandrohdezma** [comment]
cc @fthomas ☝🏼
