### ISSUE TITLE
Failed to load artifact migrations: DecodingFailure

### ISSUE THREAD

**Issue by fdietze** [scala-steward-org/scala-steward-action#365]
```
Run scala-steward-org/scala-steward-action@v2
✓ Connected to Maven Central
✓ Coursier installed, version: 2.0.16
✓ Github Token provided as input
✓ User information retrieved from Github
✓ Github Repository set to: priceloop/nocode.
✓ Scala Steward workspace created
Trying to restore workspace contents from cache...
✓ scalafmt installed, version: scalafmt 3.5.8
✓ scalafix installed, version: 0.10.0
Launching org.scala-steward:scala-steward-core_2.13:0.14.0
  2022-06-01 22:24:09,486 INFO   
    ____            _         ____  _                             _
   / ___|  ___ __ _| | __ _  / ___|| |_ _____      ____ _ _ __ __| |
   \___ \ / __/ _` | |/ _` | \___ \| __/ _ \ \ /\ / / _` | '__/ _` |
    ___) | (_| (_| | | (_| |  ___) | ||  __/\ V  V / (_| | | | (_| |
   |____/ \___\__,_|_|\__,_| |____/ \__\___| \_/\_/ \__,_|_|  \__,_|
   v0.14.0
   
  Error: java.lang.Throwable: Failed to load artifact migrations from https://raw.githubusercontent.com/scala-steward-org/scala-steward/master/modules/core/src/main/resources/artifact-migrations.v2.conf
  Error: 	at org.scalasteward.core.update.artifact.ArtifactMigrationsLoader$$anonfun$decodeMigrations$1.applyOrElse(ArtifactMigrationsLoader.scala:50)
  Error: 	at org.scalasteward.core.update.artifact.ArtifactMigrationsLoader$$anonfun$decodeMigrations$1.applyOrElse(ArtifactMigrationsLoader.scala:50)
  Error: 	at scala.PartialFunction$AndThen.applyOrElse(PartialFunction.scala:288)
  Error: 	at cats.ApplicativeError.$anonfun$recoverWith$1(ApplicativeError.scala:130)
  Error: 	at recoverWith$extension @ org.scalasteward.core.io.process$.$anonfun$slurp$3(process.scala:63)
  Error: 	at blocking @ org.scalasteward.core.io.FileAlg$$anon$1.ensureExists(FileAlg.scala:100)
  Error: 	at blocking @ org.scalasteward.core.io.FileAlg$$anon$1.ensureExists(FileAlg.scala:100)
  Error: 	at blocking @ org.scalasteward.core.io.FileAlg$$anon$1.ensureExists(FileAlg.scala:100)
  Error: 	at make @ org.http4s.okhttp.client.OkHttpBuilder$.defaultOkHttpClient(OkHttpBuilder.scala:202)
  Error: 	at make @ org.http4s.okhttp.client.OkHttpBuilder$.defaultOkHttpClient(OkHttpBuilder.scala:202)
  Error: 	at flatMap @ org.scalasteward.core.update.artifact.ArtifactMigrationsLoader.$anonfun$loadMigrations$2(ArtifactMigrationsLoader.scala:46)
  Error: 	at map @ org.scalasteward.core.update.artifact.ArtifactMigrationsLoader.$anonfun$loadMigrations$2(ArtifactMigrationsLoader.scala:46)
  Error: Caused by: DecodingFailure(Attempt to decode value on failed cursor, List(DownField(artifactIdAfter), MoveRight, MoveRight, MoveRight, MoveRight, MoveRight, MoveRight, MoveRight, MoveRight, MoveRight, MoveRight, MoveRight, MoveRight, MoveRight, MoveRight, MoveRight, MoveRight, MoveRight, MoveRight, MoveRight, MoveRight, MoveRight, MoveRight, MoveRight, MoveRight, MoveRight, MoveRight, MoveRight, MoveRight, MoveRight, MoveRight, MoveRight, MoveRight, MoveRight, MoveRight, MoveRight, MoveRight, MoveRight, MoveRight, MoveRight, MoveRight, MoveRight, MoveRight, MoveRight, MoveRight, MoveRight, MoveRight, MoveRight, MoveRight, MoveRight, MoveRight, MoveRight, MoveRight, MoveRight, MoveRight, MoveRight, MoveRight, MoveRight, MoveRight, MoveRight, MoveRight, MoveRight, MoveRight, MoveRight, MoveRight, MoveRight, MoveRight, MoveRight, MoveRight, MoveRight, MoveRight, MoveRight, MoveRight, MoveRight, MoveRight, MoveRight, MoveRight, MoveRight, MoveRight, MoveRight, MoveRight, MoveRight, DownArray, DownField(changes)))
Error:  ✕ Launching org.scala-steward:scala-steward-core_2.13:0.14.0 failed
```

**Comment by alejandrohdezma** [comment]
Hey @fdietze, thanks for the heads up, [this should be fixed now](https://github.com/scala-steward-org/scala-steward/commit/3dbb80a28d45f5a70202ce66175c7cbc909d197a).

**Comment by fdietze** [comment]
It's working now. Thank you so much for the quick fix!

**Comment by alejandrohdezma** [comment]
All the credit is for @xuwei-k who fixed it :)
